### ISSUE TITLE
提一个建议

### ISSUE THREAD

**Issue by Tom9998** [hldh214/PUBG#10]
我发现war模式和derank模式问题。他们两个都是在飞机上直接退出重进，没有达到掉分的效果，能不能使其中一个达到下飞机乱走30秒，然后退出的效果

**Comment by hldh214** [comment]
目前计算 rank 分的方式是看本局排名
上飞机直接退和乱走 30 秒没啥区别吧

**Comment by Tom9998** [comment]
额，是这样计分的呀，我昨天试了一把发现没掉分，可能眼花了

**Comment by hldh214** [comment]
他这个计分有延迟, 你多挂几把, 过几个小时回来再看分就好了
