### ISSUE TITLE
希望增加超时重连功能

### ISSUE THREAD

**Issue by madlifer** [hldh214/PUBG#4]
1.测试在 match making 卡住的情况下不会自动重启大厅
2.测试在服务器繁忙情况下只会进行reconnect 一次

**Comment by hldh214** [comment]
1. 一直是我头疼的问题, 因为卡住的时候窗体是未响应状态, 不知道如何处理比较好(pkill?)
2. reconnect 是正常的 while 逻辑之一, 你下次遇到这个问题给游戏截个图贴上来看看, 可能是找图出问题了

**Comment by madlifer** [comment]
match making卡住  窗体是可以响应的啊. 就是停留在下方有matchmaking但进不去的状态,可以单独找一下这个图,然后多少秒后再找一下,如果还能找到就ECS重启大厅.我不知道怎么找图.不会弄

**Comment by hldh214** [comment]
好的明白了
之前误以为你说的是卡在进入游戏之前的黑底界面了

**Comment by madlifer** [comment]
嗯. 大佬可以看一下这个项目,里面有超时重连的东西. https://github.com/peleon02
