### ISSUE TITLE
Cannot make it work. :(

### ISSUE THREAD

**Issue by davy4R5** [hldh214/PUBG#6]
What im duin
1. copied the project
2. extract it to folder
3. install all requirements
4. tryin to start it - after the line of (python ./main.py -t solo-squad -m bps) window switching from cmd to game but after nothin happens, game just stayn open and thats all (stuck in menu) https://imgur.com/a/z0G5q
5. After terminate the cmd line i got this - (File "./main.py", line 187, in <module> sleep <5> KeyboardInterrupt . - https://imgur.com/a/aGk5Q

my ingame settings - https://imgur.com/a/1bgrT

does i smth miss? or its a bug after they added the event mode to live?

**Comment by hldh214** [comment]
Thanks for report.
are you using Windows server or something without monitor/graphic card?
cuz the core function of this script is [ImageGrab](http://pillow.readthedocs.io/en/5.1.x/reference/ImageGrab.html#PIL.ImageGrab.PIL.ImageGrab.grab), which required monitor support (you cannot even close the lid if using laptop).

I look forward to hearing from you <3

**Comment by davy4R5** [comment]
Ehmhmh, just tested it with my laptop (win 10, x64, 1607build), working perfectly!
But in main PC (win7, 64x Pro) still can't fix it.

**Comment by davy4R5** [comment]
on the main PC im using windows 7 professional (license) 
and some disabled services, maybe some of them affect it?
the list services which i disabled.
### 
    * Desktop Window Manager Session Manager (i don't use the Aero theme)
    * Diagnostic Policy Service
    * Distributed Link Tracking Client
    * IP Helper
    * Offline Files
    * Portable Device Enumerator Service
    * Print Spooler (If you don't have Printer)
    * Protected Storage
    * Remote Registry (Always disable it for Security purposes)
    * Secondary Logon
    * Security Center
    * Tablet PC Input Service
    * TCP/IP NetBIOS Helper
    * Themes ( i lkie the Windows Classic theme)
    * Windows Error Reporting Service
    * Windows Media Center Service Launcher
    * Windows Search (If you don't use Windows Search feature frequently)
    * Windows Time (If you don't want to update system tray clock time using Internet)
    * Computer Browser
    * Server
